plugins: duplicates fetchart embedart

import:
  copy: no
  move: no
  write: yes
  duplicate_action: keep

duplicates:
  keys: [artist, title]
  strict: yes

fetchart:
  auto: yes
  sources:
    - coverart
    - itunes
    - amazon
    - albumart

embedart:
  auto: no
